-- Expand the global exercise catalog with common barbell, dumbbell, machine,
-- cable, and bodyweight movements across push/pull/legs.

-- Guard against re-running this (or any future reseed) creating duplicate
-- global catalog entries.
create unique index if not exists exercises_global_name_key
  on public.exercises (lower(name))
  where user_id is null;

insert into public.exercises (name, category) values
  ('Incline Barbell Bench Press', 'push'),
  ('Decline Barbell Bench Press', 'push'),
  ('Dumbbell Bench Press', 'push'),
  ('Incline Dumbbell Bench Press', 'push'),
  ('Decline Dumbbell Bench Press', 'push'),
  ('Dumbbell Shoulder Press', 'push'),
  ('Arnold Press', 'push'),
  ('Machine Chest Press', 'push'),
  ('Machine Shoulder Press', 'push'),
  ('Smith Machine Bench Press', 'push'),
  ('Smith Machine Shoulder Press', 'push'),
  ('Cable Chest Fly', 'push'),
  ('Dumbbell Chest Fly', 'push'),
  ('Pec Deck Machine', 'push'),
  ('Cable Crossover', 'push'),
  ('Push-up', 'push'),
  ('Incline Push-up', 'push'),
  ('Decline Push-up', 'push'),
  ('Dips', 'push'),
  ('Weighted Dips', 'push'),
  ('Machine Dips', 'push'),
  ('Close-Grip Bench Press', 'push'),
  ('Skull Crushers', 'push'),
  ('Dumbbell Tricep Extension', 'push'),
  ('Overhead Tricep Extension', 'push'),
  ('Cable Tricep Pushdown', 'push'),
  ('Cable Tricep Rope Pushdown', 'push'),
  ('Tricep Kickback', 'push'),
  ('Lateral Raise', 'push'),
  ('Cable Lateral Raise', 'push'),
  ('Machine Lateral Raise', 'push'),
  ('Front Raise', 'push'),
  ('Cable Front Raise', 'push'),
  ('Rear Delt Fly', 'push'),
  ('Cable Rear Delt Fly', 'push'),
  ('Reverse Pec Deck', 'push'),
  ('Landmine Press', 'push'),
  ('Push Press', 'push'),
  ('Z Press', 'push'),
  ('Single Arm Dumbbell Press', 'push'),
  ('Floor Press', 'push'),
  ('Svend Press', 'push'),
  ('Cable Chest Press', 'push'),
  ('Plate Front Raise', 'push'),
  ('Upright Row', 'push'),
  ('High Incline Dumbbell Press', 'push'),
  ('Guillotine Press', 'push'),
  ('Dumbbell Pullover', 'push'),
  ('Bench Dip', 'push'),
  ('JM Press', 'push'),
  ('Diamond Push-up', 'push'),
  ('Romanian Deadlift', 'pull'),
  ('Sumo Deadlift', 'pull'),
  ('Rack Pull', 'pull'),
  ('Trap Bar Deadlift', 'pull'),
  ('Dumbbell Row', 'pull'),
  ('T-Bar Row', 'pull'),
  ('Cable Row', 'pull'),
  ('Seated Cable Row', 'pull'),
  ('Chest Supported Row', 'pull'),
  ('Machine Row', 'pull'),
  ('Pendlay Row', 'pull'),
  ('Meadows Row', 'pull'),
  ('Lat Pulldown', 'pull'),
  ('Wide Grip Lat Pulldown', 'pull'),
  ('Close Grip Lat Pulldown', 'pull'),
  ('Reverse Grip Pulldown', 'pull'),
  ('Straight Arm Pulldown', 'pull'),
  ('Chin-up', 'pull'),
  ('Neutral Grip Pull-up', 'pull'),
  ('Assisted Pull-up', 'pull'),
  ('Face Pull', 'pull'),
  ('Cable Face Pull', 'pull'),
  ('Shrugs', 'pull'),
  ('Dumbbell Shrugs', 'pull'),
  ('Barbell Shrugs', 'pull'),
  ('Cable Shrugs', 'pull'),
  ('Barbell Curl', 'pull'),
  ('EZ Bar Curl', 'pull'),
  ('Dumbbell Curl', 'pull'),
  ('Hammer Curl', 'pull'),
  ('Concentration Curl', 'pull'),
  ('Preacher Curl', 'pull'),
  ('Cable Curl', 'pull'),
  ('Cable Hammer Curl', 'pull'),
  ('Incline Dumbbell Curl', 'pull'),
  ('Spider Curl', 'pull'),
  ('Zottman Curl', 'pull'),
  ('Reverse Curl', 'pull'),
  ('21s Bicep Curl', 'pull'),
  ('Machine Bicep Curl', 'pull'),
  ('Good Morning', 'pull'),
  ('Back Extension', 'pull'),
  ('Hyperextension', 'pull'),
  ('Seal Row', 'pull'),
  ('Inverted Row', 'pull'),
  ('Renegade Row', 'pull'),
  ('Single Arm Cable Row', 'pull'),
  ('Wide Grip Cable Row', 'pull'),
  ('Landmine Row', 'pull'),
  ('Kroc Row', 'pull'),
  ('Front Squat', 'legs'),
  ('Goblet Squat', 'legs'),
  ('Bulgarian Split Squat', 'legs'),
  ('Dumbbell Lunge', 'legs'),
  ('Walking Lunge', 'legs'),
  ('Reverse Lunge', 'legs'),
  ('Leg Press', 'legs'),
  ('Hack Squat', 'legs'),
  ('Smith Machine Squat', 'legs'),
  ('Leg Extension', 'legs'),
  ('Leg Curl', 'legs'),
  ('Seated Leg Curl', 'legs'),
  ('Lying Leg Curl', 'legs'),
  ('Stiff Leg Deadlift', 'legs'),
  ('Hip Thrust', 'legs'),
  ('Barbell Hip Thrust', 'legs'),
  ('Glute Bridge', 'legs'),
  ('Cable Kickback', 'legs'),
  ('Machine Hip Thrust', 'legs'),
  ('Step-up', 'legs'),
  ('Box Step-up', 'legs'),
  ('Calf Raise', 'legs'),
  ('Standing Calf Raise', 'legs'),
  ('Seated Calf Raise', 'legs'),
  ('Leg Press Calf Raise', 'legs'),
  ('Donkey Calf Raise', 'legs'),
  ('Sissy Squat', 'legs'),
  ('Zercher Squat', 'legs'),
  ('Pistol Squat', 'legs'),
  ('Box Squat', 'legs'),
  ('Overhead Squat', 'legs'),
  ('Belt Squat', 'legs'),
  ('Sumo Squat', 'legs'),
  ('Curtsy Lunge', 'legs'),
  ('Lateral Lunge', 'legs'),
  ('Cossack Squat', 'legs'),
  ('Glute Ham Raise', 'legs'),
  ('Nordic Curl', 'legs'),
  ('Adductor Machine', 'legs'),
  ('Abductor Machine', 'legs'),
  ('Cable Pull Through', 'legs'),
  ('Kettlebell Swing', 'legs'),
  ('Single Leg Press', 'legs'),
  ('Single Leg Deadlift', 'legs'),
  ('Farmer''s Carry', 'legs'),
  ('Trap Bar Squat', 'legs'),
  ('Jefferson Squat', 'legs'),
  ('Machine Squat', 'legs'),
  ('Smith Machine Lunge', 'legs'),
  ('Wall Sit', 'legs'),
  ('Split Squat', 'legs')
on conflict (lower(name)) where user_id is null do nothing;
